import { Inter } from "next/font/google";
import "/src/app/globals.css";
import { MainLayout } from "@/components/layouts/MainLayout";
import { LanguageContextProvider } from "@/context/languageContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className={module.css}>
            <LanguageContextProvider>
                <body suppressHydrationWarning={true} className={inter.className}>
                    <MainLayout>
                        {children}
                    </MainLayout>
                </body>
            </LanguageContextProvider>
        </html>
    );
}
