import { Inter } from "next/font/google";
import "/src/app/globals.css";
import { MainLayout } from "@/components/layouts/MainLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className={module.css}>
            <body suppressHydrationWarning={true} className={inter.className}>
                <MainLayout>
                    {children}
                </MainLayout>
            </body>
        </html>
    );
}
