import { Inter } from "next/font/google";
import "./globals.css";
import { LanguageContextProvider } from "@/context/languageContext";
import { MainLayout } from "@/components/layouts/MainLayout";
import { UserContextProvider } from "@/context/userContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className={module.css}>
            <body suppressHydrationWarning={true} className={inter.className}>
                <LanguageContextProvider>
                    {children}
                </LanguageContextProvider>
                <h1>Ko co o nav 3 root</h1>
            </body>
        </html>
    );
}
