import { Inter } from "next/font/google";
import "./globals.css";
import { UserContextProvider } from "@/context/userContext";
import { LanguageContextProvider } from "@/context/languageContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <UserContextProvider>
                <LanguageContextProvider>
                    <body suppressHydrationWarning={true} className={inter.className}>
                        {children}
                    </body>
                </LanguageContextProvider>
            </UserContextProvider>
        </html>
    );
}

